org: orgDemo
app: appDemo
stage: dev
component: egg
name: eggDemo

inputs:
  # src: ./src
  region: ap-guangzhou
  functionName: eggDemo
  runtime: Nodejs10.15
  apigatewayConf:
    protocols:
      - http
      - https
    environment: release
